# Generated by Django 4.2.11 on 2026-02-06 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='created_at',
        ),
    ]
