# Generated by Django 4.2.11 on 2026-02-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_doctoravailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('checked_in', 'Checked In'), ('in_progress', 'Doctor Seeing'), ('completed', 'Completed'), ('cancelled_by_patient', 'Cancelled by Patient'), ('doctor_unavailable', 'Doctor Unavailable')], default='scheduled', max_length=20),
        ),
    ]
