# Generated by Django 4.2.11 on 2026-02-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='report_pdf',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
