# Generated by Django 4.2.11 on 2026-02-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_report_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
