# Generated by Django 4.2.11 on 2026-02-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointment_patient_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='report_pdf',
            field=models.URLField(blank=True, null=True),
        ),
    ]
