# Generated by Django 4.2.11 on 2026-02-20 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0007_alter_appointment_report_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctoravailability',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='is_available',
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='capacity',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to=settings.AUTH_USER_MODEL),
        ),
    ]
