# Generated by Django 4.2.11 on 2026-02-20 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_alter_doctoravailability_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.doctoravailability'),
        ),
    ]
